<div class="container">
  <h2>Login</h2>
  <h6>----------------------------------------</h6>
<?=

$title = 'login - InputFilter';
$this->headTitle($title);

$form = $this->form;
$form->setName('login');
$form->setAttributes([
    'class'=>'form-horizontal',
    'id' => 'login-form',
    'action' => '#'
]);
$form->prepare();
?>

    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3 wow fadeInUp delay-05s">
        <div class="form">


          <?= $this->form()->openTag($form); //<form>?>

            <div class="form-group">
              <?= $this->formLabel($form->get('email'));?>
                <?= $this->formElement($form->get('email'));?>
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>
            <div class="form-group">
              <?= $this->formLabel($form->get('password'));?>
                <?= $this->formElement($form->get('password'));?>
                <?= $this->formElementErrors($form->get('password')); ?>
            </div>
            <div class="form-group">
              <?= $this->formLabel($form->get('remember'));?>
                <?= $this->formElement($form->get('remember'));?>
            </div>
            <div class="form-group">
              <?= $this->formRow($form->get('submit'));?>
            </div>

            <?= $this->form()->closeTag();//</form> ?>
        </div>
      </div>
    </div>
</div>
