<?php
$title = 'List User';
$this->headTitle($title);
$users = $this->users;
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <?= $this->flashMessenger()->render('success',['alert', 'alert-success']); ?>
    </div>
    <div class="col-xs-8 col-sm-8 col-md-10 col-lg-10 col-md-offset-1 wow fadeInUp delay-05s">
        <h2><?= $title ?></h2>
        <div class ="col-md-4 col-md-offset-0" >
            <a class="btn btn-primary" href="<?= $this->url('user',['action'=>'add']) ?>" role="button">
            <span class="glyphicon glyphicon-plus" aria-hidden="true">Add</a>
        </div>
        <table class="table table-hover table-condensed ">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Username</th>
                    <th>RFID</th>
                    <th>Email</th>
                    <th>Fullname</th>
                    <th>Birthday</th>
                    <th>Phone</th>
                    <th>Role</th>
                    <th>Option</th>
                </tr>
            </thead>
            <tbody>
                <?php $stt = 1;
                foreach($users as $user): ?>
                <tr>
                    <td><?= $stt;  ?></td>
                    <td><?= $this->escapeHtml($user->getUSERNAME());  ?></td>
                    <td><?= $this->escapeHtml($user->getRFID());  ?></td>
                    <td><?= $this->escapeHtml($user->getEMAIL());  ?></td>
                    <td><?= $this->escapeHtml($user->getFULLNAME());  ?></td>
                    <td><?= $user->getBIRTHDAY()->format('d-m-Y');  ?></td>
                    <td><?= $this->escapeHtml($user->getPHONE());  ?></td>
                    <td><?= $this->escapeHtml($user->getROLE()); ?></td>
                    <td>
                        <a href="<?= $this->url('user',['action'=>'edit','id'=>$this->escapeHtml($user->getId())]) ?>">Edit</a>
                        |
                        <a href="<?= $this->url('user',['action'=>'delete','id'=>$this->escapeHtml($user->getId())]) ?>">Delete</a>
                        |
                        <a href="<?= $this->url('user',['action'=>'change-password','id'=>$this->escapeHtml($user->getId())]) ?>">Change Password</a>
                    </td>
                </tr>
                <?php 
                    $stt++;
                    endforeach;
                ?>
            </tbody>
        </table>
    </div>
</div>