<?php
$title = "Report RFID";
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>

<?= $this->flashMessenger()->render('success',['alert', 'alert-success']); ?>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3 wow fadeInUp delay-05s">
        <div class="form">
            <h2><?= $this->escapeHtml($title)?></h2>
            <?= $this->form()->openTag($form); // <form>?>

            <div class="form-group">
                <?= $this->formLabel($form->get('rfid'));?>
                <?= $this->formElement($form->get('rfid'));?>
                <?= $this->formElementErrors($form->get('rfid')); ?>
            </div>

            <div class="text-right">
                <?=$this->formRow($form->get('btnSubmit'));?>
            </div>

            <?= $this->form()->closeTag($form); // </form>?>
        </div>
    </div>
</div>