<?php
    $this->headTitle('Reset Pass');
?>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <?= $this->flashMessenger()->render('error',['alert', 'alert-danger']); ?>
        <?= $this->flashMessenger()->render('success',['alert', 'alert-success']); ?>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3 wow fadeInUp delay-05s">
        <div class="form">
            <h2><?= $this->escapeHtml('Change Pass')?></h2>
            <?= $this->form()->openTag($form); // <form>?>
            
                <div class="form-group">
                    <?= $this->formLabel($form->get('email'));?>
                    <?= $this->formElement($form->get('email'));?>
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('CAPTCHA'));?>
                    <?= $this->formElement($form->get('CAPTCHA'));?>
                    <?= $this->formElementErrors($form->get('CAPTCHA')); ?>
                </div>

                <?= $this->formElement($form->get('csrf'));  ?>

                <div class="text-right">
                    <?=$this->formRow($form->get('btnSubmit'));?>
                </div>

            <?= $this->form()->closeTag($form); // </form>?>
        </div>
    </div>
</div>