<?= $this->doctype() ?>

  <html lang="en">

  <head>
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, maximum-scale=1"> -->

    <!-- Check headTitle -->
    <?= $this->headTitle('CEEC')->setSeparator(' - ')->setAutoEscape(false); ?>
     <?= $this->headMeta()
        ->appendName('viewport', 'width = device-width, maximum-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE = edge')
     ?>

     <!-- Le styles -->
     <?= $this->headLink(['rel' => 'shortcut icon', 'type' =>
         'image/vnd.microsoft.icon',
         'href' => $this->basePath('favicon.png')])
         ->prependStylesheet($this->basePath('css/style.css'))
         ->prependStylesheet($this->basePath('css/animate.css'))
         ->prependStylesheet($this->basePath('css/bootstrap.css'))
         ->prependStylesheet($this->basePath('css/font-awesome.css'))
         ->prependStylesheet($this->basePath('css/responsive.css'))
         ->prependStylesheet($this->basePath('css/magnific-popup.css'))
         ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
         ->prependStylesheet($this->basePath('https://fonts.googleapis.com/css?family=Montserrat:400,700'))
         ->prependStylesheet($this->basePath('https://fonts.googleapis.com/css?family=Open+Sans:400,300,800italic,700italic,600italic,400italic,300italic,800,700,600'))
      ?>
    <!-- <title>Homepage</title>
    <link rel="icon" href="favicon.png" type="image/png">
    <link rel="shortcut icon" href="favicon.ico" type="img/x-icon"> -->

    <!-- <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,800italic,700italic,600italic,400italic,300italic,800,700,600' rel='stylesheet' type='text/css'> -->

    <!-- <link href="css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="css/style.css" rel="stylesheet" type="text/css">
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="css/responsive.css" rel="stylesheet" type="text/css">
    <link href="css/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="css/animate.css" rel="stylesheet" type="text/css"> -->

    <!-- Scripts -->
      <?= $this->headScript()
         ->prependFile($this->basePath('contactform/contactform.js'))
         ->prependFile($this->basePath('js/magnific-popup.js'))
         ->prependFile($this->basePath('js/classie.js'))
         ->prependFile($this->basePath('js/wow.js'))
         ->prependFile($this->basePath('js/jquery.isotope.js'))
         ->prependFile($this->basePath('js/jquery.easing.1.3.js'))
         ->prependFile($this->basePath('js/jquery-scrolltofixed.js'))
         ->prependFile($this->basePath('js/bootstrap.js'))
         ->prependFile($this->basePath('js/bootstrap.min.js'))
         ->prependFile($this->basePath('js/jquery.1.8.3.min.js'))
         ->prependFile($this->basePath('js/popper.min.js'))
      ?>

    <!-- <script type="text/javascript" src="js/jquery.1.8.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/jquery-scrolltofixed.js"></script>
    <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="js/jquery.isotope.js"></script>
    <script type="text/javascript" src="js/wow.js"></script>
    <script type="text/javascript" src="js/classie.js"></script>
    <script type="text/javascript" src="js/magnific-popup.js"></script>
    <script src="contactform/contactform.js"></script> -->
  </head>

  <body>
    <?php if ($this->url() == $this->url('home')) { $isHome = 1?>
    <header class="header" id="header">
      <!--header-start-->
      <div class="container">
        <figure class="logo animated fadeInDown delay-07s">
          <a href="#"><img src="<?php echo $this->basePath('img/logo.png'); ?>" alt=""></a>
        </figure>
        <h1 class="animated fadeInDown delay-07s">Welcome To CEEC</h1>
        <ul class="we-create animated fadeInUp delay-1s">
          <li>Computer Engineering Embedded Club</li>
        </ul>
        <a class="link animated fadeInUp delay-1s servicelink" href="#service">Get Started</a>
      </div>
    </header>
  <?php } else $isHome = 0?>
    <!--header-end-->

    <nav class="main-nav-outer" id="test">
      <!--main-nav-start-->
      <div class="container">
        <ul class="main-nav">
          <li><a href=<?php if ($isHome == 0) echo $this->url('home') ?>#header>Home</a></li>
          <li><a href=<?php if ($isHome == 0) echo $this->url('home') ?>#service>Services</a></li>
          <li><a href=<?php if ($isHome == 0) echo $this->url('home') ?>#Portfolio>Portfolio</a></li>
          <li class="small-logo"><a href=<?php if ($isHome == 0) echo $this->url('home') ?>#header><img src="<?php echo $this->basePath('img/small-logo.png'); ?>" alt=""></a></li>
          <li><a href=<?php if ($isHome == 0) echo $this->url('home') ?>#client>Clients</a></li>
          <li><a href=<?php if ($isHome == 0) echo $this->url('home') ?>#team>Team</a></li>
          <li><a href=<?php if ($isHome == 0) echo $this->url('home') ?>#contact>Contact</a></li>
        </ul>
        <a class="res-nav_click" href="#"><i class="fa fa-bars"></i></a>
      </div>
    </nav>
    <!--main-nav-end-->

    <div class="container">
      <?=
        $this->content
      ?>

        <hr>
        <footer class="footer">
          <div class="container">
            <div class="footer-logo"><a href="<?= $this->url('about') ?>"><img src="<?php echo $this->basePath('img/footer-logo.png'); ?>" alt=""></a></div>
            <span class="copyright">&copy; Knight Theme. All Rights Reserved</span>
            <div class="credits">
              <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Knight
        -->
              Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
              Editted by <a href ="https://www.facebook.com/Computer.Engineering.Embedded.Club">CEEC</a>
              <p>&copy; 2010 -
                <?= date('Y') ?> by Computer Engineering Embedded Club @ All rights reserved.</p>
            </div>
          </div>
        </footer>
    </div>
    <?= $this->inlineScript() ?>
      <script type="text/javascript">
        $(document).ready(function(e) {

          $('#test').scrollToFixed();
          $('.res-nav_click').click(function() {
            $('.main-nav').slideToggle();
            return false

          });

          $('.Portfolio-box').magnificPopup({
            delegate: 'a',
            type: 'image'
          });

        });
      </script>

      <script>
        wow = new WOW({
          animateClass: 'animated',
          offset: 100
        });
        wow.init();
      </script>


      <script type="text/javascript">
        $(window).load(function() {

          $('.main-nav li a, .servicelink').bind('click', function(event) {
            var $anchor = $(this);

            $('html, body').stop().animate({
              scrollTop: $($anchor.attr('href')).offset().top - 102
            }, 1500, 'easeInOutExpo');
            /*
            if you don't want to use the easing effects:
            $('html, body').stop().animate({
            	scrollTop: $($anchor.attr('href')).offset().top
            }, 1000);
            */
            if ($(window).width() < 768) {
              $('.main-nav').hide();
            }
            event.preventDefault();
          });
        })
      </script>

      <script type="text/javascript">
        $(window).load(function() {


          var $container = $('.portfolioContainer'),
            $body = $('body'),
            colW = 375,
            columns = null;


          $container.isotope({
            // disable window resizing
            resizable: true,
            masonry: {
              columnWidth: colW
            }
          });

          $(window).smartresize(function() {
            // check if columns has changed
            var currentColumns = Math.floor(($body.width() - 30) / colW);
            if (currentColumns !== columns) {
              // set new column count
              columns = currentColumns;
              // apply width to container manually, then trigger relayout
              $container.width(columns * colW)
                .isotope('reLayout');
            }

          }).smartresize(); // trigger resize to set container width
          $('.portfolioFilter a').click(function() {
            $('.portfolioFilter .current').removeClass('current');
            $(this).addClass('current');

            var selector = $(this).attr('data-filter');
            $container.isotope({

              filter: selector,
            });
            return false;
          });

        });

        $(document).ready(function () {
          $('#dtVerticalScrollExample').DataTable({
            "scrollY": "200px",
            "scrollCollapse": true,
            });
            $('.dataTables_length').addClass('bs-select');
          });
      </script>

  </body>

  </html>
