<div class="container">
  <h2>Value From Form</h2>
  <h6>---------------------------------------</h6>
<?php

  $form = $this->form;
  $form->prepare();
 ?>
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3 wow fadeInUp delay-05s">
        <div class="form">
          <div id="sendmessage">Your message has been sent. Thank you!</div>
          <div id="errormessage"></div>
          <?= $this->form()->openTag($form); // <form>?>

            <div class="form-group">
            <?= $this->formRow($form->get('MSSV'));?>
            <div class="validation"></div>
            </div>

            <div class="form-group">
            <?= $this->formRow($form->get('NAME'));?>
            <div class="validation"></div>
            </div>

            <div class="form-group">
            <?= $this->formRow($form->get('EMAIL'));?>
            <div class="validation"></div>
            </div>

            <div class="form-group">
            <?= $this->formRow($form->get('MYSELECT'));?>
            <div class="validation"></div>
            </div>

            <div class="form-group">
            <?= $this->formRow($form->get('myFile'));?>
            <div class="validation"></div>
            </div>

            <div class="form-group">
            <?= $this->formRow($form->get('CAPTCHA'));?>
            <div class="validation"></div>
            </div>

            <div class = "text-center">
              <?= $this->formRow($form->get('myResetButton')); ?>
              <?= $this->formRow($form->get('submitButton')); ?>
            </div>
            <?= $this->form()->closeTag($form); // </form>?>
        </div>
      </div>
    </div>
</div>
